### ISSUE TITLE
Suggestion: Notification on copy

### ISSUE THREAD

**Issue by rokf** [RonnyDo/ColorPicker#22]
It'd be cool if a notification appeared when the copy to clipboard button is clicked.

Its really simple to implement, example here: https://github.com/keyilan/swatches/blob/master/src/MainWindow.vala#L438

**Comment by RonnyDo** [comment]
Hey rokf, thanks for your input! I considered to implenent it, but I don't think it will increase the users experience. In my opinion notifications are meant for actions that happen in the background, for example the notifications of the elementary terminal if a task finishes but the window isn't focused. The notification doesn't pop up if the terminal is your active window. Furthermore a CTRL+C in a text editor of your choice doesn't trigger a notification either. A notification would rather distract your workflow.

**Comment by rokf** [comment]
Makes sense :+1:

**Comment by Hedronmx** [comment]
It should have at least some kind of feedback.
