### ISSUE TITLE
Don't add the same color to color history twice

### ISSUE THREAD

**Issue by lmberg** [RonnyDo/ColorPicker#24]
Color history should not show the same color twice. Otherwise, the user might lose other colors saved in history if he or she selects the same color twice by accident.

![image](https://user-images.githubusercontent.com/12778831/29176219-84a64628-7deb-11e7-84dd-57000fdbe466.png)
(this is not very useful)

**Comment by RonnyDo** [comment]
Thanks for the great idea! I would like to implement it like this:
* if a non-existent color had been picked, the left-most color is kicked out and the new one is added to the right (like the way it's implemented now)
* if a already existent color had been picked, the color just get selected (like you would click on it in the color history)
Would love to hear your opinion!

**Comment by lmberg** [comment]
Yep. thats exactly what I had in mind.
