### ISSUE TITLE
Release on Juno

### ISSUE THREAD

**Issue by micahilbery** [RonnyDo/ColorPicker#47]
Love the app and hope to see a release for Juno :slightly_smiling_face:

**Comment by eliocamp** [comment]
I really miss Color Picker in Juno :cry:

**Comment by o-alquimista** [comment]
Looks like the developer has been away for a few months. Wish I knew how to maintain this.

**Comment by RonnyDo** [comment]
I just released the elementaryos Juno version of Colorpicker! Enjoy guys and thank you for your heart warming support :-)
