### ISSUE TITLE
App don't behave as expected

### ISSUE THREAD

**Issue by raibtoffoletto** [RonnyDo/ColorPicker#59]
Just installed in my system and the app don't work.
Doesn't matter where I click, I only have two colors in the history, gray and white.
Also the magnifying lens don't show the color I am hovering on the screen,
it stays with weird artifacts.

Using: elementary OS 5.0 Juno x86_64 
Kernel: 4.15.0-47-generic 
Resolution: 1366x768, 1920x1080, 1024x768
(using external monitor HDMI and laptop screen)

ASUS N53SV 1.0 
CPU: Intel i7-2630QM (8) @ 2.900GHz
GPU: Intel 2nd Generation Core Processor Family 
Memory: 7879MiB 

Later on I'll try to compile myself to see if there is any change in behaviour.

**Comment by RonnyDo** [comment]
Could you reproduce the bug with your own compilation?

**Comment by raibtoffoletto** [comment]
You can close this bug report, I re-tried the app now and it seems to be working as expected in my laptop and desktop. Probably one of the system updates/drivers we got in the past few months solved the problem. Thanks!
