### ISSUE TITLE
Add Graphics category to your .desktop

### ISSUE THREAD

**Issue by danrabbit** [RonnyDo/ColorPicker#6]
Since your app deals with graphics you should add the `Graphics` category to your .desktop file in addition to `Utility`. Adding more categories will help people discover your app.

You can see the list of accepted main categories [here](https://standards.freedesktop.org/menu-spec/latest/apa.html) and additional categories [here](https://standards.freedesktop.org/menu-spec/latest/apas02.html)

**Comment by RonnyDo** [comment]
Thanks for your advice!
