### ISSUE TITLE
Flickering when moving

### ISSUE THREAD

**Issue by ChildishGiant** [RonnyDo/ColorPicker#64]
https://gfycat.com/classicoldfashionedamericancrocodile

![classicoldfashionedamericancrocodile](https://thumbs.gfycat.com/ClassicOldfashionedAmericancrocodile-size_restricted.gif)

I tried screen recordings, even at 60fps but I couldn't catch this so I used my phone. Whenever the magnifier moves, it takes a moment to refresh so you can see through it and it flickers. This also happens when moving with the arrow keys but that doesn't show.

**Comment by dagolinuxoid** [comment]
Confirmed

**Comment by dagolinuxoid** [comment]
No flickering anymore -  @ChildishGiant close the issue if you're not experiencing it anymore.

**Comment by ChildishGiant** [comment]
I've since done a fresh install and no longer have the issue.
