### ISSUE TITLE
Question: is the binary name purposely com.github.ronnydo.colorpicker? 

### ISSUE THREAD

**Issue by Svintooo** [RonnyDo/ColorPicker#85]
The binary name I get after compilation is: com.github.ronnydo.colorpicker

I have never seen a binary name as strange as this before, so I just wanted to ask if this is on purpose? And if so, why was it chosen? Does it have to do with how Elemenaty OS works?

**Comment by RonnyDo** [comment]
Hi @Svintooo thanks for reaching out! Yes indeed that has to do with the RDNN app naming convention elementary Os announced a couple of years ago. I found this blog post from long time ago https://medium.com/elementaryos/cleaning-up-app-codenames-ef9fc637ddef
So the coding guidelines for developing eOs apps recommend it as well for third party apps (like this). Elementary has a pretty nice automated all development pipeline. I believe it wouldn't work without a proper naming even. Hope I could enlighten you a little ;-) 
Cheers, Ronny

**Comment by Svintooo** [comment]
Thank you! This was very informative.
