### ISSUE TITLE
Can't open on Manjaro after compile

### ISSUE THREAD

**Issue by rolodoom** [RonnyDo/ColorPicker#88]
After a succesful compile can't open the programa. Here is the error from the terminal

`(com.github.ronnydo.colorpicker:43149): Gtk-WARNING **: 05:15:30.049: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(com.github.ronnydo.colorpicker:43149): Gdk-CRITICAL **: 05:15:30.111: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed
double free or corruption (out)
Aborted (core dumped)
`

Any help is appreciated.

Thanks

**Comment by BBaoVanC** [comment]
I am also getting this on Arch Linux (using the [AUR package](https://aur.archlinux.org/packages/color-picker))

**Comment by BBaoVanC** [comment]
Looks like the same issue as #87

**Comment by rolodoom** [comment]
Yep.
